name: izdb
description: A new Flutter project.


publish_to: 'none'

version: 1.1.3+17

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1
  hijri: ^3.0.0
  intl: ^0.18.0
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  flutter_qiblah: ^2.0.2
  google_maps_flutter: ^2.1.8
  geolocator: ^9.0.2
  just_audio: ^0.9.27
  material_color_generator: ^1.1.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  firebase_messaging: ^14.2.0
  firebase_storage: ^11.0.9
  url_launcher: ^6.1.4
  cloud_functions: ^4.0.6
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.4
  firebase_analytics: ^10.0.8
  badges: ^2.0.3
  flutter_typeahead: ^4.0.0
  fluttertoast: ^8.0.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter_native_splash:
  background_image: assets/images/splash.png
#  color: "#f8f0de"
  android_12:
    background_image: assets/images/splash.png
#    color: "#f8f0de"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0




flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/audio/
    - assets/json/
    - assets/images/
    - assets/images/prayer_times/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf

